---
apiVersion: v1
kind: Service
metadata:
  name: emojify-api
spec:
  selector:
    app: emojify-api
  ports:
  - protocol: TCP
    port: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-api
  labels:
    app: emojify-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-api
  template:
    metadata:
      labels:
        app: emojify-api
    spec:
      containers:
      - name: emojify-api
        image: "nicholasjackson/emojify-api:0.5.6"
        imagePullPolicy: IfNotPresent
        command: ["/service/emojify-api"]
        args: [
          "-bind-address=0.0.0.0:9090",
          "-allow-origin=*",
          "-authn-disable=true",
          "-path=/"
        ]
        env:
        - name: FACEBOX
          value: http://emojify-facebox.default.svc.cluster.local:8080
