---
apiVersion: v1
kind: Service
metadata:
  name: emojify-website
spec:
  selector:
    app: emojify-website
  ports:
  - protocol: TCP
    port: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emojify-website-configmap
data:
  config: |
    window.env = {};
    window.env.config = {
      AUTH_URL: '/auth',
      API_URL: '/api/',
      PAYMENT_URL: '/api/payments',
      HOME_URL: '/',
      OAUTH_ENABLED: false,
      AUTH_DISABLED: true,
      PAYMENT_ENABLED: true
    };

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emojify-website
  labels:
    app: emojify-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emojify-website
  template:
    metadata:
      labels:
        app: emojify-website

    spec:
      volumes:
      - name: config
        configMap:
          name: emojify-website-configmap
          items:
          - key: config
            path: env.js
      containers:
      - name: emojify-website
        image: "nicholasjackson/emojify-website:0.5.8"
        imagePullPolicy: Always
        command: ["serve"]
        args: [
          "-s",
          "-l", "tcp://0.0.0.0:5000",
          "build"
        ]

        volumeMounts:
        - name: config
          mountPath: /app/build/config/
          readOnly: true
